# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form_Main(object):
    def setupUi(self, Form_Main):
        if not Form_Main.objectName():
            Form_Main.setObjectName(u"Form_Main")
        Form_Main.resize(752, 500)
        Form_Main.setMinimumSize(QSize(752, 500))
        Form_Main.setMaximumSize(QSize(752, 500))
        Form_Main.setStyleSheet(u"background :rgb(68, 68, 68)rgb(44, 44, 44);\n"
"color:white;")
        self.frame = QFrame(Form_Main)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 730, 70))
        self.frame.setTabletTracking(False)
        self.frame.setStyleSheet(u"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Plain)
        self.btn_add_product = QPushButton(self.frame)
        self.btn_add_product.setObjectName(u"btn_add_product")
        self.btn_add_product.setGeometry(QRect(310, 20, 121, 41))
        self.btn_add_product.setStyleSheet(u"background :green;\n"
"color: white;\n"
"font: 75 italic 12pt \"Arial\";")
        self.btn_Accounts = QPushButton(self.frame)
        self.btn_Accounts.setObjectName(u"btn_Accounts")
        self.btn_Accounts.setGeometry(QRect(450, 20, 121, 41))
        self.btn_Accounts.setStyleSheet(u"background :green;\n"
"color: white;\n"
"font: 75 italic 12pt \"Arial\";")
        self.btn_Express = QPushButton(self.frame)
        self.btn_Express.setObjectName(u"btn_Express")
        self.btn_Express.setGeometry(QRect(590, 20, 121, 41))
        self.btn_Express.setStyleSheet(u"background :green;\n"
"color: white;\n"
"font: 75 italic 12pt \"Arial\";")
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 221, 51))
        self.frame_2 = QFrame(Form_Main)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 90, 730, 80))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 111, 41))
        self.comboBox_filtro = QComboBox(self.frame_2)
        self.comboBox_filtro.setObjectName(u"comboBox_filtro")
        self.comboBox_filtro.setGeometry(QRect(150, 30, 111, 22))
        self.comboBox_filtro.setStyleSheet(u"color:white;")
        self.line_buscar = QLineEdit(self.frame_2)
        self.line_buscar.setObjectName(u"line_buscar")
        self.line_buscar.setGeometry(QRect(290, 30, 171, 21))
        self.line_buscar.setMaxLength(20)
        self.line_buscar.setClearButtonEnabled(True)
        self.btn_Buscar = QPushButton(self.frame_2)
        self.btn_Buscar.setObjectName(u"btn_Buscar")
        self.btn_Buscar.setGeometry(QRect(490, 20, 81, 31))
        self.btn_Buscar.setStyleSheet(u"background :blue;\n"
"color: white;\n"
"font: 75 italic 12pt \"Arial\";")
        self.btn_actualizar = QPushButton(self.frame_2)
        self.btn_actualizar.setObjectName(u"btn_actualizar")
        self.btn_actualizar.setGeometry(QRect(590, 20, 81, 31))
        self.btn_actualizar.setStyleSheet(u"background :blue;\n"
"color: white;\n"
"font: 75 italic 12pt \"Arial\";")
        self.tableWidget = QTableWidget(Form_Main)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(20, 180, 501, 281))
        self.tableWidget.setStyleSheet(u"background :rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 italic 12pt \"Arial\";")
        self.label_2 = QLabel(Form_Main)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 470, 101, 20))
        self.label_3 = QLabel(Form_Main)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(150, 470, 47, 13))
        self.frame_3 = QFrame(Form_Main)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(530, 170, 211, 291))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.label_5 = QLabel(self.frame_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 20, 91, 21))
        self.line_nombre_cliente = QLineEdit(self.frame_3)
        self.line_nombre_cliente.setObjectName(u"line_nombre_cliente")
        self.line_nombre_cliente.setGeometry(QRect(100, 20, 101, 20))
        self.line_nombre_cliente.setMaxLength(10)
        self.line_nombre_cliente.setClearButtonEnabled(True)
        self.label_6 = QLabel(self.frame_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 91, 21))
        self.label_deuda_anterior = QLabel(self.frame_3)
        self.label_deuda_anterior.setObjectName(u"label_deuda_anterior")
        self.label_deuda_anterior.setGeometry(QRect(110, 50, 91, 21))
        self.label_8 = QLabel(self.frame_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 80, 41, 21))
        self.line_kg_pz = QLineEdit(self.frame_3)
        self.line_kg_pz.setObjectName(u"line_kg_pz")
        self.line_kg_pz.setGeometry(QRect(50, 80, 61, 21))
        self.line_kg_pz.setMaxLength(3)
        self.line_kg_pz.setClearButtonEnabled(True)
        self.line_precio = QLineEdit(self.frame_3)
        self.line_precio.setObjectName(u"line_precio")
        self.line_precio.setGeometry(QRect(140, 80, 61, 21))
        self.line_precio.setMaxLength(3)
        self.line_precio.setClearButtonEnabled(True)
        self.label_9 = QLabel(self.frame_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(120, 80, 16, 21))
        self.comboBox_Producto = QComboBox(self.frame_3)
        self.comboBox_Producto.setObjectName(u"comboBox_Producto")
        self.comboBox_Producto.setGeometry(QRect(80, 110, 69, 22))
        self.comboBox_Producto.setStyleSheet(u"")
        self.label_10 = QLabel(self.frame_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 110, 61, 21))
        self.label_11 = QLabel(self.frame_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 140, 61, 21))
        self.label_Total = QLabel(self.frame_3)
        self.label_Total.setObjectName(u"label_Total")
        self.label_Total.setGeometry(QRect(80, 140, 81, 21))
        self.label_12 = QLabel(self.frame_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 170, 51, 21))
        self.line_recivo = QLineEdit(self.frame_3)
        self.line_recivo.setObjectName(u"line_recivo")
        self.line_recivo.setGeometry(QRect(60, 170, 71, 21))
        self.line_recivo.setMaxLength(5)
        self.line_recivo.setClearButtonEnabled(True)
        self.label_13 = QLabel(self.frame_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 200, 61, 21))
        self.label_Acuenta = QLabel(self.frame_3)
        self.label_Acuenta.setObjectName(u"label_Acuenta")
        self.label_Acuenta.setGeometry(QRect(80, 200, 81, 21))
        self.btn_save = QPushButton(self.frame_3)
        self.btn_save.setObjectName(u"btn_save")
        self.btn_save.setGeometry(QRect(70, 250, 75, 23))
        self.btn_save.setStyleSheet(u"background:green;\n"
"color:white;")
        self.label_14 = QLabel(Form_Main)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(520, 470, 61, 21))
        self.label_fecha = QLabel(Form_Main)
        self.label_fecha.setObjectName(u"label_fecha")
        self.label_fecha.setGeometry(QRect(580, 470, 151, 21))

        self.retranslateUi(Form_Main)

        QMetaObject.connectSlotsByName(Form_Main)
    # setupUi

    def retranslateUi(self, Form_Main):
        Form_Main.setWindowTitle(QCoreApplication.translate("Form_Main", u"PVM", None))
        self.btn_add_product.setText(QCoreApplication.translate("Form_Main", u"Add Product", None))
        self.btn_Accounts.setText(QCoreApplication.translate("Form_Main", u"Accounts", None))
        self.btn_Express.setText(QCoreApplication.translate("Form_Main", u"Expenses", None))
        self.label_4.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic;\">Bienvenido a PVM</span></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Buscar por:</span></p></body></html>", None))
        self.line_buscar.setPlaceholderText(QCoreApplication.translate("Form_Main", u" ejem. 25/08/2099 o tripa", None))
        self.btn_Buscar.setText(QCoreApplication.translate("Form_Main", u"Buscar", None))
        self.btn_actualizar.setText(QCoreApplication.translate("Form_Main", u"Actualizar", None))
        self.label_2.setText(QCoreApplication.translate("Form_Main", u"Cantidad ventas:", None))
        self.label_3.setText(QCoreApplication.translate("Form_Main", u"      0", None))
        self.label_5.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p><span style=\" font-size:10pt;\">Name - Client: </span></p></body></html>", None))
        self.line_nombre_cliente.setPlaceholderText(QCoreApplication.translate("Form_Main", u"ejem. javier", None))
        self.label_6.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p><span style=\" font-size:9pt;\">Deuda anterior :</span></p></body></html>", None))
        self.label_deuda_anterior.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">0</span></p><p align=\"center\"><br/></p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p>KG - PZ :</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.line_kg_pz.setToolTip(QCoreApplication.translate("Form_Main", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.line_kg_pz.setPlaceholderText(QCoreApplication.translate("Form_Main", u"ejem. 100", None))
#if QT_CONFIG(tooltip)
        self.line_precio.setToolTip(QCoreApplication.translate("Form_Main", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.line_precio.setPlaceholderText(QCoreApplication.translate("Form_Main", u"ejem. $$$", None))
        self.label_9.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p>$ :</p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p><span style=\" font-size:9pt;\">Producto:</span></p></body></html>", None))
        self.label_11.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p><span style=\" font-size:9pt;\">Total :</span></p></body></html>", None))
        self.label_Total.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">0</span></p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p><span style=\" font-size:9pt;\">Recibo :</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.line_recivo.setToolTip(QCoreApplication.translate("Form_Main", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.line_recivo.setPlaceholderText(QCoreApplication.translate("Form_Main", u"ejem. 10000", None))
        self.label_13.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p><span style=\" font-size:9pt;\">Acuenta :</span></p></body></html>", None))
        self.label_Acuenta.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">0</span></p></body></html>", None))
        self.btn_save.setText(QCoreApplication.translate("Form_Main", u"Save", None))
        self.label_14.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Fecha :</span></p></body></html>", None))
        self.label_fecha.setText(QCoreApplication.translate("Form_Main", u"<html><head/><body><p><span style=\" font-size:9pt;\">None</span></p></body></html>", None))
    # retranslateUi

